apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: app
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
